PayrollManagementWeb/Models/Employee.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PayrollManagementWeb.Models
{
    public class Employee
    {
        [Key]
        public int EmployeeId { get; set; }
        [Required]
        [DisplayName("Employee Name")]
        [MinLength(3)]
        public string Name { get; set; }
        [DisplayName("Employee Code")]
        [Range(101, 10000, ErrorMessage = "Employee Code must be between 101 - 9999")]
        public int EmployeeCode { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }

        public DateTime CreatedAt { get; set; }
        public int Salary { get; set; }
    }
}

PayrollManagementWeb/Models/ErrorViewModel.cs
namespace PayrollManagementWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PayrollManagementWeb/Areas/Customer/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Payroll.Models;
using PayrollManagementWeb.Models;

namespace PayrollManagementWeb.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PayrollManagementWeb/Controllers/AttendanceController.cs
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.EntityFrameworkCore.SqlServer.Query.Internal;
using Payroll.DataAccess.Repository.IRepository;
using Payroll.Models;

namespace PayrollManagementWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AttendanceController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        public AttendanceController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index(DateOnly? date = null)
        {

            List<Employee> objEmployeeList = _unitOfWork.Employee.GetAll().ToList();
            List<Attendance> objAttendancelist = _unitOfWork.Attendance.GetAll().ToList();
            if (date.HasValue)
            {
                TempData["selectedDate"] = date.Value;
                List<Attendance> chooseDate = objAttendancelist.FindAll((ad) => ad.AttendanceDate == date.Value).ToList();
                return View(chooseDate);

            }

            return View(objAttendancelist);
        }

        public IActionResult Create()
        {
            List<Employee> objEmployeeList = _unitOfWork.Employee.GetAll().ToList();
            List<Attendance> objAttendancelist = _unitOfWork.Attendance.GetAll().ToList();

            AttendanceVM attendance = new AttendanceVM()
            {
                Employees = objEmployeeList,
                Attendances = new List<Attendance>()
            };
            return View(attendance);
        }
        [HttpPost]
        public IActionResult Create(AttendanceVM atten)
        {
            return View();
        }
    }
}

PayrollManagementWeb/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Payroll.DataAccess.Data;
using Payroll.DataAccess.Repository.IRepository;
using Payroll.Models;

namespace PayrollManagementWeb.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _db;
        public EmployeeController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List<Employee> objEmployeeList = _db.Employees.ToList();
            return View(objEmployeeList);
        }


        public IActionResult Create()
        {
            return View();
        }
        //[HttpPost]
        //public IActionResult Create(Employee obj)
        //{
        //    if (ModelState.IsValid)
        //    {

        //        _unitOfWork.Employee.Add(obj);
        //        _unitOfWork.Save();
        //        TempData["success"] = "Employee created successfully";
        //        return RedirectToAction("Index");
        //    }
        //    return View();
        //}

        //public IActionResult Edit(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }

        //    Employee? employeeFromDb = _unitOfWork.Employee.Get(e => e.EmployeeId == id);
        //    //Employee? employeeFromDb1 = _db.Employees.FirstOrDefault(e => e.EmployeeId == id);
        //    //Employee? employeeFromDb2 = _db.Employees.Where(u => u.EmployeeId == id).FirstOrDefault();
        //    if (employeeFromDb == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(employeeFromDb);
        //}
        //[HttpPost]
        //public IActionResult Edit(Employee obj)
        //{
        //    if (ModelState.IsValid)
        //    {

        //        _unitOfWork.Employee.Update(obj);
        //        _unitOfWork.Save();
        //        TempData["success"] = "Employee updated successfully";
        //        return RedirectToAction("Index");
        //    }

        //    return View();
        //}

        //public IActionResult Delete(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }

        //    Employee? employeeFromDb = _unitOfWork.Employee.Get(e => e.EmployeeId == id);
        //    //Employee? employeeFromDb1 = _db.Employees.FirstOrDefault(e => e.EmployeeId == id);
        //    //Employee? employeeFromDb2 = _db.Employees.Where(u => u.EmployeeId == id).FirstOrDefault();
        //    if (employeeFromDb == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(employeeFromDb);
        //}
        //[HttpPost, ActionName("Delete")]
        //public IActionResult DeletePOST(int? id)
        //{
        //    Employee? obj = _unitOfWork.Employee.Get(e => e.EmployeeId == id);

        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }

        //    _unitOfWork.Employee.Remove(obj);
        //    _unitOfWork.Save();
        //    TempData["success"] = "Employee deleted successfully";

        //    return RedirectToAction("Index");
        //}
    }
}

PayrollManagementWeb/Areas/Customer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PayrollManagementWeb/Views/Attendance/Create.cshtml
@model Payroll.Models.AttendanceVM
<div class="container">
    <form method="post">
        <div class="row mt-4 mb-3 ">
            <div class="col-md-6"><h4 class="text-primary">Fill Attendance</h4></div>
            <div class="col-md-6 text-end">
                <h4>

                    <label>@DateTime.Now.ToString("dd-MMM-yyyy")</label>

                </h4>
            </div>
            <hr class="mt-2" />
        </div>
        <table class="table table-hover " style="width: 100%;">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Status</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody >
                @foreach (var emp in Model.Employees)
                {

                    <tr>
                        <td>@emp.Name @emp.EmployeeCode</td>
                        <td id="attendanceStatus(@emp.EmployeeId)" asp-for=""></td>
                        <td>
                            <a class="btn btn-success" onclick="attendance(@emp.EmployeeId,'Present')"> Present</a>
                            <a class="btn btn-danger" onclick="attendance(@emp.EmployeeId,'Absent')"> Absent</a>
                        </td>
                    </tr>


                }
            </tbody>
        </table>

        <div class="row mt-4">
            <div class="col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a asp-controller="Employee" asp-action="Index" class="btn btn-outline-primary">Back To List</a>
            </div>
        </div>
    </form>
</div>
<script>
    function attendance(empId, attMark){
    let attendanceStatus = document.getElementById("attendanceStatus("+empId+")")
        if(attMark == "Present"){
            attendanceStatus.style.color = "#198754";
            attendanceStatus.innerHTML= "Present";
        }else{
            attendanceStatus.style.color = "#dc3545";
            attendanceStatus.innerHTML= "Absent";
        }
    }
</script>

PayrollManagementWeb/Views/Attendance/Index.cshtml
@model List<Attendance>
<div class="container">
    <div class="row mt-4 mb-3 ">
        <div class="col-md-6"><h4 class="text-primary">Attendance List</h4></div>
        
        <hr class="mt-2" />
    </div>
    <div class="row">
        <div class="col-md-4">
            <label class="form-label">Choose Date</label>
            <input type="date" class="form-control" id="filterDate" onchange="filterAttendance()" />
        </div>
        
        <div class="col-md-8 text-end">
            @if (TempData["selectedDate"] != null)
            {
            <label class="form-label">Attendance Date</label>
            <h4 class="text-primary">@TempData["selectedDate"]</h4>
            }
            else
            {
            <h4 class="text-primary">All</h4>
                
            }
        </div>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Attendance Date</th>
                <th scope="col">Present</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>@obj.Employee.Name @obj.Employee.EmployeeCode</td>
                    <td >@obj.AttendanceDate</td>
                    <td>@(obj.Present ? "Present" : "Absent")</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    function filterAttendance(){
        console.log("Hello world")
        let fDate  = document.getElementById("filterDate").value;
        window.location.href="Attendance/Index?date=" + fDate.toString();
        console.log(fDate)
        
    }
</script>

PayrollManagementWeb/Views/Employee/Create.cshtml
@model Employee
<div class="container">
    <form method="post">
        <div class="row mt-4 mb-3">
            <div class="col-md-6"><h4 class="text-primary">Add Employee</h4></div>
            
            <div class="col-md-6 text-end">
                    <h4>

                        <label asp-for="CreatedAt">@DateTime.Now.ToString("dd-MMM-yyyy")</label>
                    </h4>
            </div>
            <hr class="mt-2" />
            <div asp-validation-summary="All"></div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label asp-for="Name" class="form-label"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="Name">
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>
            </div>
            <div class="col-md-6">
                <label asp-for="EmployeeCode" class="form-label"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="EmployeeCode">
                    <span class="text-danger" asp-validation-for="EmployeeCode"></span>
                </div>
            </div>
            <div class="col-md-6">
                <label asp-for="Department" class="form-label"></label>
                <div class="col-sm-10">
                    <select asp-for="Department" class="form-control form-select">
                        <option>IT</option>
                        <option>Account</option>
                        <option>Sales</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <label asp-for="Designation" class="form-label"></label>
                <div class="col-sm-10">
                    <select asp-for="Designation" class="form-control form-select">
                        <option>Manager</option>
                        <option>HR</option>
                        <option>Junior-Engneer</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <label asp-for="Salary" class="form-label"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="Salary">
                </div>
            </div>

        </div>
        <div class="row mt-4">
            <div class="col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Create</button>
                <a asp-controller="Employee" asp-action="Index" class="btn btn-outline-primary">Back To List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

PayrollManagementWeb/Views/Employee/Delete.cshtml
@model Employee
<div class="container">
    <form method="post">
        <input asp-for="EmployeeId" hidden />
        <div class="row mt-4 mb-3">
            <div class="col-md-6"><h4 class="text-primary">Delete Employee</h4></div>

            <div class="col-md-6 text-end">
                <h4>

                    <label asp-for="CreatedAt">@DateTime.Now.ToString("dd-MMM-yyyy")</label>
                </h4>
            </div>
            <hr class="mt-2" />
        </div>
        <div class="row">
            <div class="col-md-6">
                <label asp-for="Name" class="form-label"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="Name" disabled>
                </div>
            </div>
            <div class="col-md-6">
                <label asp-for="EmployeeCode" class="form-label"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="EmployeeCode" disabled>
                </div>
            </div>
            <div class="col-md-6">
                <label asp-for="Department" class="form-label"></label>
                <div class="col-sm-10">
                    <select asp-for="Department" disabled class="form-control form-select">
                        <option>IT</option>
                        <option>Account</option>
                        <option>Sales</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <label asp-for="Designation" class="form-label"></label>
                <div class="col-sm-10">
                    <select asp-for="Designation" disabled class="form-control form-select">
                        <option>Manager</option>
                        <option>HR</option>
                        <option>Junior-Engneer</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <label asp-for="Salary" class="form-label"></label>
                <div class="col-sm-10">
                    <input class="form-control" disabled asp-for="Salary">
                </div>
            </div>

        </div>
        <div class="row mt-4">
            <div class="col-md-12 text-center">
                <button type="submit" class="btn btn-danger">Delete</button>
                <a asp-controller="Employee" asp-action="Index" class="btn btn-outline-primary">Back To List</a>
            </div>
        </div>
    </form>
</div>

PayrollManagementWeb/Views/Employee/Edit.cshtml
@model Employee
<div class="container">
    <form method="post">
    <input asp-for="EmployeeId" hidden/>
        <div class="row mt-4 mb-3">
            <div class="col-md-6"><h4 class="text-primary">Edit Employee</h4></div>

            <div class="col-md-6 text-end">
                <h4>

                    <label asp-for="CreatedAt">@DateTime.Now.ToString("dd-MMM-yyyy")</label>
                </h4>
            </div>
            <hr class="mt-2" />
            <div asp-validation-summary="All"></div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label asp-for="Name" class="form-label"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="Name">
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>
            </div>
            <div class="col-md-6">
                <label asp-for="EmployeeCode" class="form-label"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="EmployeeCode">
                    <span class="text-danger" asp-validation-for="EmployeeCode"></span>
                </div>
            </div>
            <div class="col-md-6">
                <label asp-for="Department" class="form-label"></label>
                <div class="col-sm-10">
                    <select asp-for="Department" class="form-control form-select">
                        <option>IT</option>
                        <option>Account</option>
                        <option>Sales</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <label asp-for="Designation" class="form-label"></label>
                <div class="col-sm-10">
                    <select asp-for="Designation" class="form-control form-select">
                        <option>Manager</option>
                        <option>HR</option>
                        <option>Junior-Engneer</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <label asp-for="Salary" class="form-label"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="Salary">
                </div>
            </div>

        </div>
        <div class="row mt-4">
            <div class="col-md-12 text-center">
                <button type="submit" class="btn btn-primary">UPDATE</button>
                <a asp-controller="Employee" asp-action="Index" class="btn btn-outline-primary">Back To List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

PayrollManagementWeb/Views/Employee/Index.cshtml
@model List<Employee>
<div class="container">
    <div class="row mt-4 mb-3 ">
        <div class="col-md-6"><h4 class="text-primary">Employee List</h4></div>
        <div class="col-md-6 text-end">
            <a class="btn btn-primary rounded-0" asp-controller="Employee" asp-action="Create"><i class="bi bi-plus-square me-2"></i>Add Employee</a>
        </div>
        <hr class="mt-2" />
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Employee Code</th>
                <th scope="col">Department</th>
                <th scope="col">Designation</th>
                <th scope="col">Date of Join</th>
                <th scope="col">Salary</th>
                <th scope="col" calspan="2">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>@obj.Name</td>
                    <td>@obj.EmployeeCode</td>
                    <td>@obj.Department</td>
                    <td>@obj.Designation</td>
                    <td>@obj.CreatedAt</td>
                    <td>@obj.Salary</td>
                    <td>
                        <a asp-controller="Employee" asp-action="Edit" asp-route-id="@obj.EmployeeId"><i class="bi bi-pencil-square"></i></a>
                    </td>
                    <td>

                        <a asp-controller="Employee" asp-action="Delete" asp-route-id="@obj.EmployeeId">
                            <i class="bi bi-trash2-fill"></i>
                        </a>
                    </td>


                </tr>
            }


        </tbody>
    </table>
</div>

PayrollManagementWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PayrollManagementWeb</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PayrollManagementWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PayrollManagementWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Attendance" asp-action="Index">Attendance</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Attendance" asp-action="Create">Attendance Fill</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - PayrollManagementWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PayrollManagementWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    
    <script type="text/javascript">
        toastr.success('@TempData["success"]')    
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["success"]')
    </script>
}